version: "3.7"

# 컴퓨터들
services:
  # 컴퓨터 이름
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      # - ./src:/myfolder/src
    ports:
      - 4000:4000

  # 컴퓨터 이름
  database:
    image: mongo:5
    ports:
      - 27017:27017
